image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - go
  - hut
sources:
  - git@git.sr.ht:~rampantmonkey/rampantmonkey.com
secrets:
  - 3e45ccba-972b-4e1d-9148-2c48414fa027
environment:
    site: rampantmonkey.com
tasks:
  - compile: |
      cd $site
      go build
  - render: |
      cd $site
      ./website
      sudo chmod 755 -R rendered
  - publish: |
      cd $site
      tar -C rendered -czvf $site.tar.gz .
      hut pages publish -d $site $site.tar.gz
