name: pages
on:
  push:
    branches:
      - main
    tags: '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build static artifact by copying site files
        run: mkdir site && cp -R CNAME index.html main.css images files writing colors contact keyboards puzzles resume site/
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
